apiVersion: apps/v1
kind: Deployment
metadata:
  name: xskriba-ambulance-ufe-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: xskriba-ambulance-ufe-label
  template:
    metadata:
      labels:
        pod: xskriba-ambulance-ufe-label
    spec:
      containers:
        - name: xskriba-ambulance-ufe-container
          image: peterskriba/ambulance-ufe
          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 8080

          resources:
            requests:
              memory: "32M"
              cpu: "0.1"
            limits:
              memory: "320M"
              cpu: "0.3"
