apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata:
  name: xskriba-ambulance-ufe
spec:
  module-uri: http://xskriba-ambulance-ufe.wac-hospital/build/ambulance-ufe.esm.js

  navigation:
    # aplication context element
    - element: xskriba-ambulance-wl-app
      attributes:
        - name: api-base
          value: http://localhost:3100/api
        - name: ambulance-id
          value: bobulova
      path: xskriba-ambulance-wl
      title: Zoznam čakajúcich xskriba
      details: Spravuje zoznam pacientov čakajúcich na vyšetrenie v ambulancii
  preload: false
  proxy: true
  hash-suffix: v1alpha2
